-- ================================================================
-- BACKEND DEL PANEL DEL PORTAFOLIO
-- Ejecuta este archivo completo en Supabase > SQL Editor.
-- Antes, reemplaza TU_CORREO_ADMIN@EJEMPLO.COM al final del archivo.
-- ================================================================

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table if not exists private.portfolio_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_portfolio_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from private.portfolio_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_portfolio_admin() from public;
grant execute on function public.is_portfolio_admin() to anon, authenticated;

create table if not exists public.portfolio_items (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('experiencia', 'educacion', 'certificacion')),
  contenido jsonb not null default '{}'::jsonb,
  orden integer not null default 0 check (orden >= 0),
  activo boolean not null default true,
  created_by uuid references auth.users(id) default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists portfolio_items_tipo_orden_idx on public.portfolio_items(tipo, orden);
create index if not exists portfolio_items_activo_idx on public.portfolio_items(activo);

create or replace function public.actualizar_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists portfolio_items_updated_at on public.portfolio_items;
create trigger portfolio_items_updated_at
before update on public.portfolio_items
for each row execute function public.actualizar_updated_at();

alter table public.portfolio_items enable row level security;
grant select on public.portfolio_items to anon, authenticated;
grant insert, update, delete on public.portfolio_items to authenticated;
grant usage, select on sequence public.portfolio_items_id_seq to authenticated;

drop policy if exists "Contenido activo visible publicamente" on public.portfolio_items;
create policy "Contenido activo visible publicamente"
on public.portfolio_items for select
to anon, authenticated
using (activo = true);

drop policy if exists "Administradores pueden leer todo" on public.portfolio_items;
create policy "Administradores pueden leer todo"
on public.portfolio_items for select
to authenticated
using ((select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden crear" on public.portfolio_items;
create policy "Administradores pueden crear"
on public.portfolio_items for insert
to authenticated
with check ((select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden actualizar" on public.portfolio_items;
create policy "Administradores pueden actualizar"
on public.portfolio_items for update
to authenticated
using ((select public.is_portfolio_admin()))
with check ((select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden eliminar" on public.portfolio_items;
create policy "Administradores pueden eliminar"
on public.portfolio_items for delete
to authenticated
using ((select public.is_portfolio_admin()));

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('portafolio', 'portafolio', true, 10485760, array['application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Administradores pueden ver archivos" on storage.objects;
create policy "Administradores pueden ver archivos"
on storage.objects for select
to authenticated
using (bucket_id = 'portafolio' and (select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden subir archivos" on storage.objects;
create policy "Administradores pueden subir archivos"
on storage.objects for insert
to authenticated
with check (bucket_id = 'portafolio' and (select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden actualizar archivos" on storage.objects;
create policy "Administradores pueden actualizar archivos"
on storage.objects for update
to authenticated
using (bucket_id = 'portafolio' and (select public.is_portfolio_admin()))
with check (bucket_id = 'portafolio' and (select public.is_portfolio_admin()));

drop policy if exists "Administradores pueden eliminar archivos" on storage.objects;
create policy "Administradores pueden eliminar archivos"
on storage.objects for delete
to authenticated
using (bucket_id = 'portafolio' and (select public.is_portfolio_admin()));

-- IMPORTANTE: crea primero el usuario en Authentication > Users y cambia este correo.
insert into private.portfolio_admins (user_id)
select id from auth.users where lower(email) = lower('luisfernandobarbosaorozco7@gmail.com')
on conflict (user_id) do nothing;